---
title: "Global Watcher- Letterboxd Visualization Project"
output: html_notebook
---

Install packages
```{r}
library(PerformanceAnalytics)
library(psych)
library(ggplot2)
library(ggthemes)
library(psychTools)
library(lattice)
library(reshape2)
library(reshape)
library(highcharter)
library(RCurl)
library(epanetReader)
library(dplyr)
library(latticeExtra)
library(grid)
library(devtools)
```

Convert csv file that I created through Globalwatcher.ipynb to movies dataframe.
```{r}
movies <- read.csv("tmdb_movies.csv")
```

I changed the original_language values to real languages. The source to the TMDB language codes are [here](https://github.com/travisbell/tmdb-web-translations/blob/main/languages/en-US.yml) 
```{r}
count = 0
for (x in movies$original_language){
  count <- count + 1
  if (x == "en") {
    movies$original_language[count] = "English"
  }
  if (x == "ko") {
    movies$original_language[count] = "Korean"
  }
   if (x == "fr") {
    movies$original_language[count] = "French"
   }
     if (x == "ja") {
    movies$original_language[count] = "Japanese"
     }
       if (x == "fi") {
    movies$original_language[count] = "Finnish"
       }
        if (x == "pt") {
    movies$original_language[count] = "Portuguese"
         }
      if (x == "hi") {
    movies$original_language[count] = "Hindi"
      }
     if (x == "it") {
    movies$original_language[count] = "Italian"
     }
     if (x == "cn") {
    movies$original_language[count] = "Chinese"
     }
     if (x == "de") {
    movies$original_language[count] = "German"
     }
     if (x == "tl") {
    movies$original_language[count] = "Tagalog"
     }
     if (x == "sv") {
    movies$original_language[count] = "Swedish"
     }
     if (x == "es") {
    movies$original_language[count] = "Spanish"
     }
     if (x == "hy") {
    movies$original_language[count] = "Armenian"
     }
     if (x == "zh") {
    movies$original_language[count] = "Chinese"
     }
}
```

Algorithm I used to check which language values I have to change.
```{r}
for (x in movies$original_language){
  if (nchar(x) == 2){
    print(x)
  } else if (nchar(x) > 2) {
    print("No language values needed to be changed!")
    break
  }
}
```

Interactive barchart of original languages vs. ratings
```{r}
fig1 <- select(movies,original_language,Rating)
ec = 0
ec_count = 0
asianc = 0
ac_count = 0
euc = 0
euc_count = 0
hc = 0
hc_count = 0

for (x in 1:393){
if (fig1$original_language[x] == "English")
    {
    if (fig1$Rating[x] != 0.0){
    ec_count = ec_count + 1
    ec = ec + fig1$Rating[x] 
    }
}else if (fig1$original_language[x] == "Korean" || fig1$original_language[x] == "Japanese"|| fig1$original_language[x] == "Hindi"|| fig1$original_language[x] == "Chinese"|| fig1$original_language[x] == "Tagalog"|| fig1$original_language[x] == "Chinese"){
  if (fig1$Rating[x] != 0.0){
    ac_count = ac_count + 1
    asianc = asianc + fig1$Rating[x] 
  }
}else if (fig1$original_language[x] == "French"|| fig1$original_language[x] == "Finnish"|| fig1$original_language[x] == "Portuguese"|| fig1$original_language[x] == "Italian"|| fig1$original_language[x] == "German"|| fig1$original_language[x] == "Swedish"|| fig1$original_language[x] == "Armenian"){
  if (fig1$Rating[x] != 0.0){
    euc_count = euc_count + 1
    euc = euc + fig1$Rating[x]
}
} else if (fig1$original_language[x] == "Spanish"){
  if (fig1$Rating[x] != 0.0){
    hc_count = hc_count + 1
    hc = hc + fig1$Rating[x]
  }
}
}

ec = ec/ec_count
asianc = asianc/ac_count
euc = euc/euc_count
hc = hc/hc_count

```

```{r}
list1 = c(ec,asianc,euc,hc)
list1categories = c("English", "Asian", "European", "Latino")

highchart() %>%
  hc_chart(type = "column") %>%
  hc_add_series(data = list1) %>%
  hc_xAxis(categories = list1categories) %>%
  hc_add_theme(hc_theme_tufte2())%>%
  hc_title(text = "Which Cultural Region has the Average Highest Movie Ratings?")

```

```{r}
moviesrevised <- select(movies, Logged_Week, Rating)

keeprows = c()
for(x in 1:393){
  if (movies$Rating[x] == 0.0){
    keeprows <- append(keeprows,x)
  }
}

moviesrevised <- moviesrevised[-c(keeprows), ] 

moviesrevised <- moviesrevised[ order(moviesrevised$Logged_Week,decreasing = FALSE),]

plot(moviesrevised$Rating ~ moviesrevised$Logged_Week, type = "o",pch = 20, col = "blue", xlab = "Logged Weeks", ylab = "Ratings")%>%
  title(main = "Does Having Letterboxd Help Diversify Your Watchlist?")
```
```{r}
d = sum(movies$Drama)
com = sum(movies$Comedy) + sum(movies$Rom_Com)
rom = sum(movies$Romance) + sum(movies$Rom_Com)
fan = sum(movies$Fantasy)
adv = sum(movies$Adventure)
act = sum(movies$Action)
crim = sum(movies$Crime)
thr = sum(movies$Thriller)
h = sum(movies$History)
dom = sum(movies$Documentary)
hor = sum(movies$Horror)
mus = sum(movies$Music)
mys = sum(movies$Mystery)
sci = sum(movies$Sci_Fi)
war = sum(movies$War)
wes = sum(movies$Western)
ani = sum(movies$Animation)

xlist<- c(d,com,rom,fan,adv,act,crim,thr,h,dom,hor,mus,mys,sci,war,wes,ani)
xnames <- c(colnames(movies[21:37]))

dev.new(width=10, height=6)
oldp <- par(mar=c(5.1, 8.1, 2.1, 1.1))
barplot(xlist, names.arg = xnames,cex.names=.7, horiz=TRUE, las=1, main = "Which Genre do I Watch the Most?")
par(oldp)
out <- barplot(xlist, names.arg = xnames,cex.names=.7, horiz=TRUE, las=1, main = "Which Genre do I Watch the Most?")
text(out, rep(-.1, 6), names(xlist), srt=45, pos=2, xpd=NA, cex=.75)

```

```{r}

```




